/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// For production deployment, use environment variables
// Fallback to hardcoded values for development
export const projectId = (import.meta.env?.VITE_SUPABASE_PROJECT_ID) || "usorqldwroecyxucmtuw"
export const publicAnonKey = (import.meta.env?.VITE_SUPABASE_ANON_KEY) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzb3JxbGR3cm9lY3l4dWNtdHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NjI2NzksImV4cCI6MjA3ODIzODY3OX0.cpSQZHkDI_yod4HSPsjUIhwSkkJX98PVJ7HjTe0i6qM"